package pyl.pojo;
/**
 * FANS_CONCERN
 * 
 * @author bianj
 * @version 1.0.0 2020-05-22
 */
public class FansConcern implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 4015488021071856077L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** fansConcernId */
    private Integer fansConcernId;

    /** fansUid */
    private Integer fansUid;

    /** fansUeamil */
    private String fansUeamil;

    /** fansUnickname */
    private String fansUnickname;

    /** concernUid */
    private Integer concernUid;

    /** concernUeamil */
    private String concernUeamil;

    /** concernUnickname */
    private String concernUnickname;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取fansConcernId
     * 
     * @return fansConcernId
     */
    public Integer getFansConcernId() {
        return this.fansConcernId;
    }

    /**
     * 设置fansConcernId
     * 
     * @param fansConcernId
     */
    public void setFansConcernId(Integer fansConcernId) {
        this.fansConcernId = fansConcernId;
    }

    /**
     * 获取fansUid
     * 
     * @return fansUid
     */
    public Integer getFansUid() {
        return this.fansUid;
    }

    /**
     * 设置fansUid
     * 
     * @param fansUid
     */
    public void setFansUid(Integer fansUid) {
        this.fansUid = fansUid;
    }

    /**
     * 获取fansUeamil
     * 
     * @return fansUeamil
     */
    public String getFansUeamil() {
        return this.fansUeamil;
    }

    /**
     * 设置fansUeamil
     * 
     * @param fansUeamil
     */
    public void setFansUeamil(String fansUeamil) {
        this.fansUeamil = fansUeamil;
    }

    /**
     * 获取fansUnickname
     * 
     * @return fansUnickname
     */
    public String getFansUnickname() {
        return this.fansUnickname;
    }

    /**
     * 设置fansUnickname
     * 
     * @param fansUnickname
     */
    public void setFansUnickname(String fansUnickname) {
        this.fansUnickname = fansUnickname;
    }

    /**
     * 获取concernUid
     * 
     * @return concernUid
     */
    public Integer getConcernUid() {
        return this.concernUid;
    }

    /**
     * 设置concernUid
     * 
     * @param concernUid
     */
    public void setConcernUid(Integer concernUid) {
        this.concernUid = concernUid;
    }

    /**
     * 获取concernUeamil
     * 
     * @return concernUeamil
     */
    public String getConcernUeamil() {
        return this.concernUeamil;
    }

    /**
     * 设置concernUeamil
     * 
     * @param concernUeamil
     */
    public void setConcernUeamil(String concernUeamil) {
        this.concernUeamil = concernUeamil;
    }

    /**
     * 获取concernUnickname
     * 
     * @return concernUnickname
     */
    public String getConcernUnickname() {
        return this.concernUnickname;
    }

    /**
     * 设置concernUnickname
     * 
     * @param concernUnickname
     */
    public void setConcernUnickname(String concernUnickname) {
        this.concernUnickname = concernUnickname;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}