package pyl.pojo;
/**
 * INFORMATION
 * 
 * @author bianj
 * @version 1.0.0 2020-05-22
 */
public class Information implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -3164544043612017324L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** informationId */
    private Integer informationId;

    /** informationEmail */
    private String informationEmail;

    /** informationContext */
    private String informationContext;

    /** postsNo */
    private String postsNo;

    /** replyId */
    private Integer replyId;

    /** informer */
    private String informer;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取informationId
     * 
     * @return informationId
     */
    public Integer getInformationId() {
        return this.informationId;
    }

    /**
     * 设置informationId
     * 
     * @param informationId
     */
    public void setInformationId(Integer informationId) {
        this.informationId = informationId;
    }

    /**
     * 获取informationEmail
     * 
     * @return informationEmail
     */
    public String getInformationEmail() {
        return this.informationEmail;
    }

    /**
     * 设置informationEmail
     * 
     * @param informationEmail
     */
    public void setInformationEmail(String informationEmail) {
        this.informationEmail = informationEmail;
    }

    /**
     * 获取informationContext
     * 
     * @return informationContext
     */
    public String getInformationContext() {
        return this.informationContext;
    }

    /**
     * 设置informationContext
     * 
     * @param informationContext
     */
    public void setInformationContext(String informationContext) {
        this.informationContext = informationContext;
    }

    /**
     * 获取postsNo
     * 
     * @return postsNo
     */
    public String getPostsNo() {
        return this.postsNo;
    }

    /**
     * 设置postsNo
     * 
     * @param postsNo
     */
    public void setPostsNo(String postsNo) {
        this.postsNo = postsNo;
    }

    /**
     * 获取replyId
     * 
     * @return replyId
     */
    public Integer getReplyId() {
        return this.replyId;
    }

    /**
     * 设置replyId
     * 
     * @param replyId
     */
    public void setReplyId(Integer replyId) {
        this.replyId = replyId;
    }

    /**
     * 获取informer
     * 
     * @return informer
     */
    public String getInformer() {
        return this.informer;
    }

    /**
     * 设置informer
     * 
     * @param informer
     */
    public void setInformer(String informer) {
        this.informer = informer;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}