package pyl.pojo;

/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.0.0
 */
/**
 * LIKES
 * 
 * @author bianj
 * @version 1.0.0 2020-05-29
 */
public class Likes implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -3713181722564780174L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** likesId */
    private Integer likesId;

    /** replyId */
    private Integer replyId;

    /** uemail */
    private String uemail;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取likesId
     * 
     * @return likesId
     */
    public Integer getLikesId() {
        return this.likesId;
    }

    /**
     * 设置likesId
     * 
     * @param likesId
     */
    public void setLikesId(Integer likesId) {
        this.likesId = likesId;
    }

    /**
     * 获取replyId
     * 
     * @return replyId
     */
    public Integer getReplyId() {
        return this.replyId;
    }

    /**
     * 设置replyId
     * 
     * @param replyId
     */
    public void setReplyId(Integer replyId) {
        this.replyId = replyId;
    }

    /**
     * 获取uemail
     * 
     * @return uemail
     */
    public String getUemail() {
        return this.uemail;
    }

    /**
     * 设置uemail
     * 
     * @param uemail
     */
    public void setUemail(String uemail) {
        this.uemail = uemail;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}