package pyl.pojo;
/**
 * POSTS_CONTENT
 * 
 * @author bianj
 * @version 1.0.0 2020-05-22
 */
public class PostsContent implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 1787204012919510718L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** postsContentId */
    private Integer postsContentId;

    /** postsNo */
    private String postsNo;

    /** content */
    private String content;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取postsContentId
     * 
     * @return postsContentId
     */
    public Integer getPostsContentId() {
        return this.postsContentId;
    }

    /**
     * 设置postsContentId
     * 
     * @param postsContentId
     */
    public void setPostsContentId(Integer postsContentId) {
        this.postsContentId = postsContentId;
    }

    /**
     * 获取postsNo
     * 
     * @return postsNo
     */
    public String getPostsNo() {
        return this.postsNo;
    }

    /**
     * 设置postsNo
     * 
     * @param postsNo
     */
    public void setPostsNo(String postsNo) {
        this.postsNo = postsNo;
    }

    /**
     * 获取content
     * 
     * @return content
     */
    public String getContent() {
        return this.content;
    }

    /**
     * 设置content
     * 
     * @param content
     */
    public void setContent(String content) {
        this.content = content;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}