package pyl.pojo;
/**
 * ROLE_RELATION
 * 
 * @author bianj
 * @version 1.0.0 2020-05-22
 */
public class RoleRelation implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -1875223441062181698L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** roleId */
    private Integer roleId;

    /** roleName */
    private String roleName;

    /** uEmail */
    private String uEmail;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取roleId
     * 
     * @return roleId
     */
    public Integer getRoleId() {
        return this.roleId;
    }

    /**
     * 设置roleId
     * 
     * @param roleId
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * 获取roleName
     * 
     * @return roleName
     */
    public String getRoleName() {
        return this.roleName;
    }

    /**
     * 设置roleName
     * 
     * @param roleName
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * 获取uEmail
     * 
     * @return uEmail
     */
    public String getUEmail() {
        return this.uEmail;
    }

    /**
     * 设置uEmail
     * 
     * @param uEmail
     */
    public void setUEmail(String uEmail) {
        this.uEmail = uEmail;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}