package pyl.pojo;
/**
 * SMODULE
 * 
 * @author bianj
 * @version 1.0.0 2020-05-22
 */
public class Smodule implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 6945585842625322153L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** smoduleId */
    private Integer smoduleId;

    /** smoduleName */
    private String smoduleName;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取smoduleId
     * 
     * @return smoduleId
     */
    public Integer getSmoduleId() {
        return this.smoduleId;
    }

    /**
     * 设置smoduleId
     * 
     * @param smoduleId
     */
    public void setSmoduleId(Integer smoduleId) {
        this.smoduleId = smoduleId;
    }

    /**
     * 获取smoduleName
     * 
     * @return smoduleName
     */
    public String getSmoduleName() {
        return this.smoduleName;
    }

    /**
     * 设置smoduleName
     * 
     * @param smoduleName
     */
    public void setSmoduleName(String smoduleName) {
        this.smoduleName = smoduleName;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}