package pyl.pojo;
/**
 * STATISTICAL
 * 
 * @author bianj
 * @version 1.0.0 2020-05-22
 */
public class Statistical implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 339797153190187288L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** stcId */
    private Integer stcId;

    /** uId */
    private Integer uId;

    /** uEmail */
    private String uEmail;

    /** postsSum */
    private Integer postsSum;

    /** collectSum */
    private Integer collectSum;

    /** hotpostsreplySum */
    private Integer hotpostsreplySum;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取stcId
     * 
     * @return stcId
     */
    public Integer getStcId() {
        return this.stcId;
    }

    /**
     * 设置stcId
     * 
     * @param stcId
     */
    public void setStcId(Integer stcId) {
        this.stcId = stcId;
    }

    /**
     * 获取uId
     * 
     * @return uId
     */
    public Integer getUId() {
        return this.uId;
    }

    /**
     * 设置uId
     * 
     * @param uId
     */
    public void setUId(Integer uId) {
        this.uId = uId;
    }

    /**
     * 获取uEmail
     * 
     * @return uEmail
     */
    public String getUEmail() {
        return this.uEmail;
    }

    /**
     * 设置uEmail
     * 
     * @param uEmail
     */
    public void setUEmail(String uEmail) {
        this.uEmail = uEmail;
    }

    /**
     * 获取postsSum
     * 
     * @return postsSum
     */
    public Integer getPostsSum() {
        return this.postsSum;
    }

    /**
     * 设置postsSum
     * 
     * @param postsSum
     */
    public void setPostsSum(Integer postsSum) {
        this.postsSum = postsSum;
    }

    /**
     * 获取collectSum
     * 
     * @return collectSum
     */
    public Integer getCollectSum() {
        return this.collectSum;
    }

    /**
     * 设置collectSum
     * 
     * @param collectSum
     */
    public void setCollectSum(Integer collectSum) {
        this.collectSum = collectSum;
    }

    /**
     * 获取hotpostsreplySum
     * 
     * @return hotpostsreplySum
     */
    public Integer getHotpostsreplySum() {
        return this.hotpostsreplySum;
    }

    /**
     * 设置hotpostsreplySum
     * 
     * @param hotpostsreplySum
     */
    public void setHotpostsreplySum(Integer hotpostsreplySum) {
        this.hotpostsreplySum = hotpostsreplySum;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}