package pyl.pojo;
/**
 * 1表示 回复，2表示@(USER_MESSAGE)
 * 
 * @author bianj
 * @version 1.0.0 2020-05-22
 */
public class UserMessage implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 2922211602446098625L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** messageId */
    private Integer messageId;

    /** uId */
    private Integer uId;

    /** uEamil */
    private String uEamil;

    /** postsNo */
    private String postsNo;

    /** postsTitle */
    private String postsTitle;

    /** otherUEmail */
    private String otherUEmail;

    /** messageContent */
    private String messageContent;

    /** type */
    private String type;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取messageId
     * 
     * @return messageId
     */
    public Integer getMessageId() {
        return this.messageId;
    }

    /**
     * 设置messageId
     * 
     * @param messageId
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * 获取uId
     * 
     * @return uId
     */
    public Integer getUId() {
        return this.uId;
    }

    /**
     * 设置uId
     * 
     * @param uId
     */
    public void setUId(Integer uId) {
        this.uId = uId;
    }

    /**
     * 获取uEamil
     * 
     * @return uEamil
     */
    public String getUEamil() {
        return this.uEamil;
    }

    /**
     * 设置uEamil
     * 
     * @param uEamil
     */
    public void setUEamil(String uEamil) {
        this.uEamil = uEamil;
    }

    /**
     * 获取postsNo
     * 
     * @return postsNo
     */
    public String getPostsNo() {
        return this.postsNo;
    }

    /**
     * 设置postsNo
     * 
     * @param postsNo
     */
    public void setPostsNo(String postsNo) {
        this.postsNo = postsNo;
    }

    /**
     * 获取postsTitle
     * 
     * @return postsTitle
     */
    public String getPostsTitle() {
        return this.postsTitle;
    }

    /**
     * 设置postsTitle
     * 
     * @param postsTitle
     */
    public void setPostsTitle(String postsTitle) {
        this.postsTitle = postsTitle;
    }

    /**
     * 获取otherUEmail
     * 
     * @return otherUEmail
     */
    public String getOtherUEmail() {
        return this.otherUEmail;
    }

    /**
     * 设置otherUEmail
     * 
     * @param otherUEmail
     */
    public void setOtherUEmail(String otherUEmail) {
        this.otherUEmail = otherUEmail;
    }

    /**
     * 获取messageContent
     * 
     * @return messageContent
     */
    public String getMessageContent() {
        return this.messageContent;
    }

    /**
     * 设置messageContent
     * 
     * @param messageContent
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }

    /**
     * 获取type
     * 
     * @return type
     */
    public String getType() {
        return this.type;
    }

    /**
     * 设置type
     * 
     * @param type
     */
    public void setType(String type) {
        this.type = type;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}