package pyl.pojo;

/**
 * USERS
 * 
 * @author bianj
 * @version 1.0.0 2020-05-22
 */
public class Users implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionuid = -7144904709720327443L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** uid */
    private int uid;

    /** uEmail */
    private String uemail;

    /** uPassword */
    private String upassword;

    /** uPhoto */
    private String uphoto;

    /** uSex */
    private String usex;

    /** uAddress */
    private String uaddress;

    /** uMaxim */
    private String umaxim;

    /** unickname */
    private String unickname;

    /** uRegistertime */
    private String uregistertime;

    /** uBan */
    private String uban;

    /** uSignintime */
    private String usignintime;

    /** uScore */
    private int uscore;

    /** uSigninday */
    private int usigninday;

    /** logintime */
    private String logintime;

	public int getUid() {
		return uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public String getUemail() {
		return uemail;
	}

	public void setUemail(String uemail) {
		this.uemail = uemail;
	}

	public String getUpassword() {
		return upassword;
	}

	public void setUpassword(String upassword) {
		this.upassword = upassword;
	}

	public String getUphoto() {
		return uphoto;
	}

	public void setUphoto(String uphoto) {
		this.uphoto = uphoto;
	}

	public String getUsex() {
		return usex;
	}

	public void setUsex(String usex) {
		this.usex = usex;
	}

	public String getUaddress() {
		return uaddress;
	}

	public void setUaddress(String uaddress) {
		this.uaddress = uaddress;
	}

	public String getUmaxim() {
		return umaxim;
	}

	public void setUmaxim(String umaxim) {
		this.umaxim = umaxim;
	}

	public String getUnickname() {
		return unickname;
	}

	public void setUnickname(String unickname) {
		this.unickname = unickname;
	}

	public String getUregistertime() {
		return uregistertime;
	}

	public void setUregistertime(String uregistertime) {
		this.uregistertime = uregistertime;
	}

	public String getUban() {
		return uban;
	}

	public void setUban(String uban) {
		this.uban = uban;
	}

	public String getUsignintime() {
		return usignintime;
	}

	public void setUsignintime(String usignintime) {
		this.usignintime = usignintime;
	}

	public int getUscore() {
		return uscore;
	}

	public void setUscore(int uscore) {
		this.uscore = uscore;
	}

	public int getUsigninday() {
		return usigninday;
	}

	public void setUsigninday(int usigninday) {
		this.usigninday = usigninday;
	}

	public String getLogintime() {
		return logintime;
	}

	public void setLogintime(String logintime) {
		this.logintime = logintime;
	}

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */
    
   

    /* This code was generated by TableGo tools, mark 2 end. */
}