package pyl.pojo;
/**
 * USER_COLLECT
 * 
 * @author bianj
 * @version 1.0.0 2020-05-22
 */
public class UserCollect implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 4975717800894707316L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** collectId */
    private Integer collectId;

    /** uId */
    private Integer uId;

    /** uEmail */
    private String uEmail;

    /** postsNo */
    private String postsNo;

    /** collectEmail */
    private String collectEmail;

    /** postsTitle */
    private String postsTitle;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取collectId
     * 
     * @return collectId
     */
    public Integer getCollectId() {
        return this.collectId;
    }

    /**
     * 设置collectId
     * 
     * @param collectId
     */
    public void setCollectId(Integer collectId) {
        this.collectId = collectId;
    }

    /**
     * 获取uId
     * 
     * @return uId
     */
    public Integer getUId() {
        return this.uId;
    }

    /**
     * 设置uId
     * 
     * @param uId
     */
    public void setUId(Integer uId) {
        this.uId = uId;
    }

    /**
     * 获取uEmail
     * 
     * @return uEmail
     */
    public String getUEmail() {
        return this.uEmail;
    }

    /**
     * 设置uEmail
     * 
     * @param uEmail
     */
    public void setUEmail(String uEmail) {
        this.uEmail = uEmail;
    }

    /**
     * 获取postsNo
     * 
     * @return postsNo
     */
    public String getPostsNo() {
        return this.postsNo;
    }

    /**
     * 设置postsNo
     * 
     * @param postsNo
     */
    public void setPostsNo(String postsNo) {
        this.postsNo = postsNo;
    }

    /**
     * 获取collectEmail
     * 
     * @return collectEmail
     */
    public String getCollectEmail() {
        return this.collectEmail;
    }

    /**
     * 设置collectEmail
     * 
     * @param collectEmail
     */
    public void setCollectEmail(String collectEmail) {
        this.collectEmail = collectEmail;
    }

    /**
     * 获取postsTitle
     * 
     * @return postsTitle
     */
    public String getPostsTitle() {
        return this.postsTitle;
    }

    /**
     * 设置postsTitle
     * 
     * @param postsTitle
     */
    public void setPostsTitle(String postsTitle) {
        this.postsTitle = postsTitle;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}