package pyl.pojo;
/**
 * 1表示 回复，2表示@(USER_MESSAGE)
 * 
 * @author bianj
 * @version 1.0.0 2020-05-22
 */
public class UserMessage implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionuid = 2922211602446098625L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** messageId */
    private int messageId;

    /** uid */
    private int uid;

    /** uemail */
    private String uemail;

    /** postsNo */
    private String postsNo;

    /** postsTitle */
    private String postsTitle;

    /** otherUemail */
    private String otherUemail;

    /** messageContent */
    private String messageContent;

    /** type */
    private String type;
    private String otherUnickname;
    private String time;
    
    
    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	/**
     * 获取messageId
     * 
     * @return messageId
     */
    public int getMessageId() {
        return this.messageId;
    }

    public String getOtherUnickname() {
		return otherUnickname;
	}

	public void setOtherUnickname(String otherUnickname) {
		this.otherUnickname = otherUnickname;
	}

	/**
     * 设置messageId
     * 
     * @param messageId
     */
    public void setMessageId(int messageId) {
        this.messageId = messageId;
    }

    /**
     * 获取uid
     * 
     * @return uid
     */
    public int getUid() {
        return this.uid;
    }

    /**
     * 设置uid
     * 
     * @param uid
     */
    public void setUid(int uid) {
        this.uid = uid;
    }

    /**
     * 获取uemail
     * 
     * @return uemail
     */
    public String getUemail() {
        return this.uemail;
    }

    /**
     * 设置uemail
     * 
     * @param uemail
     */
    public void setUemail(String uemail) {
        this.uemail = uemail;
    }

    /**
     * 获取postsNo
     * 
     * @return postsNo
     */
    public String getPostsNo() {
        return this.postsNo;
    }

    /**
     * 设置postsNo
     * 
     * @param postsNo
     */
    public void setPostsNo(String postsNo) {
        this.postsNo = postsNo;
    }

    /**
     * 获取postsTitle
     * 
     * @return postsTitle
     */
    public String getPostsTitle() {
        return this.postsTitle;
    }

    /**
     * 设置postsTitle
     * 
     * @param postsTitle
     */
    public void setPostsTitle(String postsTitle) {
        this.postsTitle = postsTitle;
    }

    /**
     * 获取otherUemail
     * 
     * @return otherUemail
     */
    public String getOtherUemail() {
        return this.otherUemail;
    }

    /**
     * 设置otherUemail
     * 
     * @param otherUemail
     */
    public void setOtherUemail(String otherUemail) {
        this.otherUemail = otherUemail;
    }

    /**
     * 获取messageContent
     * 
     * @return messageContent
     */
    public String getMessageContent() {
        return this.messageContent;
    }

    /**
     * 设置messageContent
     * 
     * @param messageContent
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }

    /**
     * 获取type
     * 
     * @return type
     */
    public String getType() {
        return this.type;
    }

    /**
     * 设置type
     * 
     * @param type
     */
    public void setType(String type) {
        this.type = type;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}