package pyl.pojo;
import java.util.Date;

/**
 * USERS
 * 
 * @author bianj
 * @version 1.0.0 2020-05-22
 */
public class Users implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -7144904709720327443L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** uId */
    private int uId;

    /** uEmail */
    private String uEmail;

    /** uPassword */
    private String uPassword;

    /** uPhoto */
    private String uPhoto;

    /** uSex */
    private String uSex;

    /** uAddress */
    private String uAddress;

    /** uMaxim */
    private String uMaxim;

    /** uNickname */
    private String uNickname;

    /** uRegistertime */
    private Date uRegistertime;

    /** uBan */
    private String uBan;

    /** uSignintime */
    private Date uSignintime;

    /** uScore */
    private int uScore;

    /** uSigninday */
    private int uSigninday;

    /** uIdentification */
    private String uIdentification;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取uId
     * 
     * @return uId
     */
    public int getUId() {
        return this.uId;
    }

    /**
     * 设置uId
     * 
     * @param uId
     */
    public void setUId(int uId) {
        this.uId = uId;
    }

    /**
     * 获取uEmail
     * 
     * @return uEmail
     */
    public String getUEmail() {
        return this.uEmail;
    }

    /**
     * 设置uEmail
     * 
     * @param uEmail
     */
    public void setUEmail(String uEmail) {
        this.uEmail = uEmail;
    }

    /**
     * 获取uPassword
     * 
     * @return uPassword
     */
    public String getUPassword() {
        return this.uPassword;
    }

    /**
     * 设置uPassword
     * 
     * @param uPassword
     */
    public void setUPassword(String uPassword) {
        this.uPassword = uPassword;
    }

    /**
     * 获取uPhoto
     * 
     * @return uPhoto
     */
    public String getuPhoto() {
        return this.uPhoto;
    }

    /**
     * 设置uPhoto
     * 
     * @param uPhoto
     */
    public void setuPhoto(String uPhoto) {
        this.uPhoto = uPhoto;
    }

    /**
     * 获取uSex
     * 
     * @return uSex
     */
    public String getUSex() {
        return this.uSex;
    }

    /**
     * 设置uSex
     * 
     * @param uSex
     */
    public void setUSex(String uSex) {
        this.uSex = uSex;
    }

    /**
     * 获取uAddress
     * 
     * @return uAddress
     */
    public String getUAddress() {
        return this.uAddress;
    }

    /**
     * 设置uAddress
     * 
     * @param uAddress
     */
    public void setUAddress(String uAddress) {
        this.uAddress = uAddress;
    }

    /**
     * 获取uMaxim
     * 
     * @return uMaxim
     */
    public String getUMaxim() {
        return this.uMaxim;
    }

    /**
     * 设置uMaxim
     * 
     * @param uMaxim
     */
    public void setUMaxim(String uMaxim) {
        this.uMaxim = uMaxim;
    }

    /**
     * 获取uNickname
     * 
     * @return uNickname
     */
    public String getUNickname() {
        return this.uNickname;
    }

    /**
     * 设置uNickname
     * 
     * @param uNickname
     */
    public void setUNickname(String uNickname) {
        this.uNickname = uNickname;
    }

    /**
     * 获取uRegistertime
     * 
     * @return uRegistertime
     */
    public Date getURegistertime() {
        return this.uRegistertime;
    }

    /**
     * 设置uRegistertime
     * 
     * @param uRegistertime
     */
    public void setURegistertime(Date uRegistertime) {
        this.uRegistertime = uRegistertime;
    }

    /**
     * 获取uBan
     * 
     * @return uBan
     */
    public String getUBan() {
        return this.uBan;
    }

    /**
     * 设置uBan
     * 
     * @param uBan
     */
    public void setUBan(String uBan) {
        this.uBan = uBan;
    }

    /**
     * 获取uSignintime
     * 
     * @return uSignintime
     */
    public Date getUSignintime() {
        return this.uSignintime;
    }

    /**
     * 设置uSignintime
     * 
     * @param uSignintime
     */
    public void setUSignintime(Date uSignintime) {
        this.uSignintime = uSignintime;
    }

    /**
     * 获取uScore
     * 
     * @return uScore
     */
    public int getUScore() {
        return this.uScore;
    }

    /**
     * 设置uScore
     * 
     * @param uScore
     */
    public void setUScore(int uScore) {
        this.uScore = uScore;
    }

    /**
     * 获取uSigninday
     * 
     * @return uSigninday
     */
    public int getUSigninday() {
        return this.uSigninday;
    }

    /**
     * 设置uSigninday
     * 
     * @param uSigninday
     */
    public void setUSigninday(int uSigninday) {
        this.uSigninday = uSigninday;
    }

    /**
     * 获取uIdentification
     * 
     * @return uIdentification
     */
    public String getUIdentification() {
        return this.uIdentification;
    }

    /**
     * 设置uIdentification
     * 
     * @param uIdentification
     */
    public void setUIdentification(String uIdentification) {
        this.uIdentification = uIdentification;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}